// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    'index',
    {
      type: 'category',
      label: 'MHCAT',
      items: [
        {
          type: 'autogenerated',
          dirName: 'MHCAT'
        }
      ]
    },
    {
      type: 'category',
      label: '所有指令',
      items: [
        {
          type: 'autogenerated',
          dirName: 'allcommands' 
        }
      ]
    },
    {
      type: 'category',
      label: '相關條款',
      items: [
        {
          type: 'autogenerated',
          dirName: 'terms'
        }
      ]
    }
  ]
}

module.exports = sidebars
